### ISSUE TITLE
Open new tab next to the word tab

### ISSUE THREAD

**Issue by laBecasse** [sanoodles/wrtranslator#1]
Hello, is it possible to open the wordreference's tab next to the tab, which contains the searched word ? Like a external link. 

It'll be great to return to the reading page, after pressing Ctrl +W.

**Comment by sanoodles** [comment]
Hi. Thanks for the feedback. I realize now that the floating link is the only way in which the new tab opens next to the original tab. Otherwise it opens at the end of the tab list. :(

I agree with your suggestion. I'll try to fix that hopefully in the next few days.

**Comment by ghost** [comment]
I only use "d" key, so i put my reading tab at the end of tab list :) Thanks for your work, roll on the update !

**Comment by sanoodles** [comment]
Hello. This should be fixed in 1.6.14 now released. Please check if it works for you when you have time. Cheers!

https://addons.mozilla.org/en-US/firefox/addon/wordreference-translator/versions/?page=1#version-1.6.14

**Comment by ghost** [comment]
You make it and it works ! Thanks you ;)

**Comment by emixam150** [comment]
![012_9a](https://cloud.githubusercontent.com/assets/8268928/16496432/1b0e7e94-3ef2-11e6-8b7a-8172de566a6f.JPG)
